Develop
andela-sgaamuwa/Checkpoint-1 pull request #1
Opened 2016-10-19 09:27 UTC by andela-sgaamuwa

2016-10-19 10:28 UTC, njirap commented
- Squash squashable commits eg.. from `ad942d1` to `44b8627`

- Improve on commit titles and bodies

- Don't push commented code

- Don't be redundant in your imports e.g. `test_amity.py` `import unittest` and `from unittest.mock import patch, PropertyMock, MagicMock, Mock`

- Install and work with pep8

- In `test_amity`, for testing of the save_state to the db you can mock the db call and assert that it has been called with the parameters

- Checkout python's `tempfile` library for creating temporary files and directories instead of having permanent ones in the test

- In `app.py` you have imported `os` but you are not using it

- `app.py` `do_reallocate_person` has nested loops. They can be made more efficient by maybe using dictionaries or comprehensions

- `amity.py` Lines 26 & 27...maybe no need for variable assignment `room`

- `amity.py` Line 65... Maybe `if staff_id in Amity.fellows.keys() + Amity.staff.keys()` . Repeat for all other ifs in the previous format

- Amity.assign_room should probably be Amity.assign_office...i.e make variables make sense

- amity.py `add_person` if statement can be refactored
L52...we probably don't need a default return message
L79...`if office is not "" or None` ...Maybe work on all if statements
Maybe `reallocate` and `reallocate_ls` can be squashed and the new function takes a third parameter of room type
`print_allocations` and `print_unallocated` maybe develop the entire text first then decide whether to output to terminal or write to file

2016-10-24 12:50 UTC, andela-sgaamuwa commented
Changes made except for:

- mocking calls to the database in save state

- using a tempfile in test_amity, it was not possible to specify the directory for the file so it kept conflicting with the code, opted to leave it as it was 

- `amity.py` line 65, dict.keys() lists can't be summed up like normal lists, so that raised an error

2017-03-11 20:36 UTC, duboviy requested changes
- Please do not use `your_dict.keys()` to iterate over a dictionary:
```python
# Bad
for key in your_dict.keys():
    ...

# Better
for key in your_dict:
    ...
```

2017-03-11 20:36 UTC, duboviy commented on classes/amity.py
> +        if room_name in room_dict.keys():
Do not use `room_dict.keys()` to iterate over a dictionary

2017-03-11 20:36 UTC, duboviy commented on app.py
> +        if room in Amity.offices.keys():
Same here

2017-03-11 20:36 UTC, duboviy commented on app.py
> +        elif room in Amity.livingspaces.keys():
Same here

2017-03-11 20:36 UTC, duboviy commented on app.py
> +        if person in Amity.fellows.keys():
Same here

2017-03-11 20:36 UTC, duboviy commented on app.py
> +        elif person in Amity.staff.keys():
Same here

2017-03-11 20:36 UTC, duboviy commented on app.py
> +        if room in Amity.offices.keys():
Same here

2017-03-11 20:36 UTC, duboviy commented on app.py
> +        elif room in Amity.livingspaces.keys():
Same here

2017-03-11 20:36 UTC, duboviy commented on app.py
> +            if person in Amity.staff.keys():
Same here

2017-03-11 20:36 UTC, duboviy commented on tests/test_amity.py
> +            self.assertIn("Python", Amity.livingspaces.keys())
Same here

2017-03-11 20:36 UTC, duboviy commented on tests/test_amity.py
> +            self.assertIn("Oculus", Amity.offices.keys())
Same here

2017-03-11 20:36 UTC, duboviy commented on classes/amity.py
> +        if staff_id in Amity.fellows.keys() or staff_id in Amity.staff.keys():
Same here

2017-03-12 13:06 UTC, andela-sgaamuwa commented on classes/amity.py
> +        if staff_id in Amity.fellows.keys() or staff_id in Amity.staff.keys():
Thank you, did not know it iterates over the keys and not the values, much appreciated

2017-03-12 18:26 UTC, duboviy commented on classes/amity.py
> +        if staff_id in Amity.fellows.keys() or staff_id in Amity.staff.keys():
You are welcome!
I'm glad that my comment was useful for you ;)

2017-04-24 13:06 UTC, merged